development:
  PORT: "3000"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: rails_starter_template_dev
  DB_HOST: localhost
  DB_PORT: "5432"
  REDIS_URL: redis://localhost:6379/1
  JWT_SECRET: some_secrete